game:
  log:
    configuration:
      path: ${LOCALAPPDATA:}/Blizzard/Hearthstone/log.config
    out:
      path: /Logs/
      file:
        screen: /LoadingScreen.log
        power: /Power.log
script:
  path: ${PROGRAMDATA:C:\ProgramData}/hs_script/
  configuration:
    file: ${script.path}/script.properties
log:
  level: info
  path: ${script.path}
logging:
  config: logback-spring.xml
  level:
    root: ${log.level}
server:
  port: 8080
#  web容器开关
spring:
  thymeleaf:
    cache: false
  main:
    web-application-type: servlet
##    web-application-type: none